const ACTION_TYPES = {
  SET_NEXT_SLIDE: 'SET_NEXT_SLIDE',
  SET_PREV_SLIDE: 'SET_PREV_SLIDE',
  SET_DURATION: 'SET_DURATION',
  SET_FULLSCREEN: 'SET_FULLSCREEN',
  SET_PAUSED: 'SET_PAUSED',
};

export default ACTION_TYPES;
